# Generated by Django 6.0.1 on 2026-01-12 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(blank=True, max_length=255, verbose_name='Proprietário')),
                ('municipio_estado', models.CharField(blank=True, max_length=255, verbose_name='Município/Estado')),
                ('proprio_ou_arrendamento', models.CharField(blank=True, max_length=50, verbose_name='Próprio ou Arrendamento')),
                ('indice_pluviometrico', models.CharField(blank=True, max_length=100, verbose_name='Índice Pluviométrico')),
                ('area_total_ha', models.CharField(blank=True, max_length=50, verbose_name='Área total em há')),
                ('area_util_pastagem_ha', models.CharField(blank=True, max_length=50, verbose_name='Área útil de pastagem em há')),
                ('quantidade_pastos', models.CharField(blank=True, max_length=50, verbose_name='Quantidade de Pastos')),
                ('tamanho_medio_pastos', models.CharField(blank=True, max_length=100, verbose_name='Tamanho médio dos pastos')),
                ('faz_rotacionado', models.BooleanField(default=False, verbose_name='Faz rotacionado')),
                ('percentual_area_rotacionada', models.CharField(blank=True, max_length=50, verbose_name='Em quantos % da área')),
                ('faz_adubacao', models.BooleanField(default=False, verbose_name='Faz Adubação')),
                ('faz_correcao_solo', models.BooleanField(default=False, verbose_name='Faz Correção de solo')),
                ('rotina_correcao', models.CharField(blank=True, max_length=255, verbose_name='Com qual rotina')),
                ('possui_area_volumoso', models.BooleanField(default=False, verbose_name='Possui área destinada a produção de volumoso')),
                ('tamanho_area_volumoso_ha', models.CharField(blank=True, max_length=50, verbose_name='Qual o tamanho (ha)')),
                ('faz_integracao_lavoura_pecuaria', models.BooleanField(default=False, verbose_name='Faz integração Lavoura Pecuária')),
                ('quantidade_animais', models.CharField(blank=True, max_length=50, verbose_name='Quantidade de Animais')),
                ('sexo_animais', models.CharField(blank=True, max_length=100, verbose_name='Sexo dos Animais')),
                ('tipo_raca_animais', models.CharField(blank=True, max_length=255, verbose_name='Tipo/raça dos Animais')),
                ('tipo_suplementacao', models.CharField(blank=True, max_length=255, verbose_name='Tipo de Suplementação')),
                ('cria_recria_ou_engorda', models.CharField(blank=True, max_length=100, verbose_name='Faz cria, recria ou engorda')),
                ('quantidade_animais_lote_peso', models.CharField(blank=True, max_length=255, verbose_name='Quantidade de Animais por lote e Peso')),
                ('compra_gado_produtor_ou_leilao', models.CharField(blank=True, max_length=100, verbose_name='Compra de gado de produtor ou Leilão')),
                ('tipo_terminacao', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Terminação à pasto/TIP/confinamento')),
                ('taxa_desfrute', models.CharField(blank=True, max_length=100, verbose_name='Taxa de Desfrute/Quantidade de Animais Vendidos/ano')),
                ('idade_media_abate', models.CharField(blank=True, max_length=50, verbose_name='Idade média de abate')),
                ('plantas_frigorificas', models.CharField(blank=True, max_length=255, verbose_name='Plantas frigoríficas mais utilizadas')),
                ('quantidade_funcionarios', models.CharField(blank=True, max_length=50, verbose_name='Quantidade de funcionários')),
                ('utiliza_software_gestao', models.BooleanField(default=False, verbose_name='Utiliza algum software de gestão')),
                ('qual_software_gestao', models.CharField(blank=True, max_length=255, verbose_name='Qual software de gestão')),
                ('possui_balanca', models.BooleanField(default=False, verbose_name='Possui Balança')),
                ('frequencia_pesagem', models.CharField(blank=True, max_length=100, verbose_name='Frequência de pesagem')),
                ('utiliza_controle_individual', models.BooleanField(default=False, verbose_name='Utiliza controle individual Brinco/chip')),
                ('tipo_brinco_chip', models.CharField(blank=True, max_length=100, verbose_name='Brinco/chip')),
                ('faz_confinamento', models.BooleanField(default=False, verbose_name='Faz confinamento')),
                ('estatico_confinamento', models.CharField(blank=True, max_length=100, verbose_name='Qual o estático')),
                ('tem_fabrica_racao', models.BooleanField(default=False, verbose_name='Tem fábrica de Ração')),
                ('possui_moinho', models.BooleanField(default=False, verbose_name='Possui Moinho')),
                ('possui_vagao_forrageiro', models.BooleanField(default=False, verbose_name='Possui Vagão Forrageiro')),
                ('capacidade_armazenagem_volumoso', models.CharField(blank=True, max_length=100, verbose_name='Capacidade de armazenagem de volumoso galpão/silo')),
                ('capacidade_armazenagem_graos', models.CharField(blank=True, max_length=100, verbose_name='Capacidade de armazenagem de grãos galpão/silo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propriedade', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
