# Generated by Django 6.0.1 on 2026-01-12 04:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_propriedade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='area_total_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Área total em há'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='area_util_pastagem_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Área útil de pastagem em há'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='capacidade_armazenagem_graos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Capacidade de armazenagem de grãos galpão/silo'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='capacidade_armazenagem_volumoso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Capacidade de armazenagem de volumoso galpão/silo'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='estatico_confinamento',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qual o estático'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='idade_media_abate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Idade média de abate'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='indice_pluviometrico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Índice Pluviométrico'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='percentual_area_rotacionada',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Em quantos % da área'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='quantidade_animais',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Animais'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='quantidade_funcionarios',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de funcionários'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='quantidade_pastos',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Pastos'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tamanho_area_volumoso_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qual o tamanho (ha)'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tamanho_medio_pastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tamanho médio dos pastos'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='taxa_desfrute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taxa de Desfrute/Quantidade de Animais Vendidos/ano'),
        ),
    ]
