# Generated by Django 4.1.5 on 2026-01-12 04:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Identificação')),
                ('tipo', models.CharField(choices=[('lote', 'Lote'), ('pasto', 'Pasto'), ('curral', 'Curral')], default='lote', max_length=10, verbose_name='Tipo')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('idade_meses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Idade (meses)')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Animais')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso (kg)')),
                ('peso_arroba', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso (@)')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de Compra/Aquisição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='usuarios.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProjecaoGanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('gmd_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='GMD (kg)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_ganho', to='usuarios.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Projeção de Ganho',
                'verbose_name_plural': 'Projeções de Ganho',
                'ordering': ['ano', 'mes'],
                'unique_together': {('lote', 'mes', 'ano')},
            },
        ),
    ]
