# Generated by Django 4.1.5 on 2026-01-12 05:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_lote_projecaoganho'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('gasto_diario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gasto Diário (R$/dia)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_nutricionais', to='usuarios.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Gasto Nutricional',
                'verbose_name_plural': 'Gastos Nutricionais',
                'ordering': ['ano', 'mes'],
                'unique_together': {('lote', 'mes', 'ano')},
            },
        ),
    ]
