# Generated by Django 4.1.5 on 2026-01-13 03:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_gastonutricional'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='ultimo_gmd_usado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Último GMD Usado (kg/dia)'),
        ),
    ]
