# Generated by Django 4.1.5 on 2026-01-13 03:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_lote_ultimo_gmd_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='ultimo_rendimento_carcaca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Último Rendimento de Carcaça (%)'),
        ),
    ]
