# Generated by Django 4.1.5 on 2026-01-13 03:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_propriedade_ultimo_rendimento_carcaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='ultimo_valor_arroba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Último Valor da @ (R$)'),
        ),
    ]
