# Generated by Django 4.1.5 on 2026-01-13 04:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_lote_ultimo_valor_arroba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venda_vacas', 'Venda de Vacas'), ('venda_bois', 'Venda de Bois'), ('venda_novilhas', 'Vendas de Novilhas'), ('venda_bezerras', 'Venda de Bezerras'), ('venda_bezerros', 'Venda de Bezerros'), ('venda_garrote', 'Venda de Garrote'), ('venda_silagem', 'Venda de Silagem')], max_length=50, verbose_name='Tipo de Receita')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='usuarios.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['ano', 'mes', 'tipo'],
                'unique_together': {('propriedade', 'tipo', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arrendamento', 'Arrendamento'), ('amortizacao', 'Amortização'), ('prolabore', 'Prólabore'), ('manutencao', 'Manutenção'), ('combustivel', 'Combustível'), ('mao_de_obra', 'Mão de Obra'), ('servicos_tecnicos', 'Serviços Técnicos'), ('supermercado', 'Supermercado'), ('itr', 'ITR'), ('fretes', 'Fretes'), ('energia', 'Energia'), ('tele_internet', 'Tele/Internet'), ('contador', 'Contador')], max_length=50, verbose_name='Tipo de Custo')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_fixos', to='usuarios.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Custo Fixo',
                'verbose_name_plural': 'Custos Fixos',
                'ordering': ['ano', 'mes', 'tipo'],
                'unique_together': {('propriedade', 'tipo', 'mes', 'ano')},
            },
        ),
    ]
