# Generated by Django 4.1.5 on 2026-01-13 04:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_receita_custofixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Mortalidade (%)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalidades', to='usuarios.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Mortalidade',
                'verbose_name_plural': 'Mortalidades',
                'ordering': ['ano', 'mes'],
                'unique_together': {('lote', 'mes', 'ano')},
            },
        ),
    ]
