# Generated by Django 6.0.1 on 2026-01-16 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_mortalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('periodo_dias', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Período (dias)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Período Personalizado',
                'verbose_name_plural': 'Períodos Personalizados',
                'ordering': ['ano', 'mes'],
            },
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='ano',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='gastonutricional',
            name='ano',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='gastonutricional',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='mortalidade',
            name='ano',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='mortalidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='projecaoganho',
            name='ano',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='projecaoganho',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ano',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='tokeninscricao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='tokeninscricao',
            name='utilizado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Utilizado'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['propriedade', 'ano', 'mes'], name='custo_fixo_prop_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['ano', 'mes'], name='custo_fixo_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['propriedade', 'ano'], name='custo_fixo_prop_ano_idx'),
        ),
        migrations.AddIndex(
            model_name='gastonutricional',
            index=models.Index(fields=['lote', 'ano', 'mes'], name='gasto_nutr_lote_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='gastonutricional',
            index=models.Index(fields=['ano', 'mes'], name='gasto_nutr_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='gastonutricional',
            index=models.Index(fields=['lote', 'ano'], name='gasto_nutr_lote_ano_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['propriedade'], name='lote_propriedade_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['nome'], name='lote_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['propriedade', 'nome'], name='lote_propriedade_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalidade',
            index=models.Index(fields=['lote', 'ano', 'mes'], name='mortalidade_lote_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalidade',
            index=models.Index(fields=['ano', 'mes'], name='mortalidade_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalidade',
            index=models.Index(fields=['lote', 'ano'], name='mortalidade_lote_ano_idx'),
        ),
        migrations.AddIndex(
            model_name='projecaoganho',
            index=models.Index(fields=['lote', 'ano', 'mes'], name='proj_ganho_lote_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='projecaoganho',
            index=models.Index(fields=['ano', 'mes'], name='proj_ganho_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='projecaoganho',
            index=models.Index(fields=['lote', 'ano'], name='proj_ganho_lote_ano_idx'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['data_criacao'], name='propriedade_data_criacao_idx'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['usuario'], name='propriedade_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['propriedade', 'ano', 'mes'], name='receita_prop_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['ano', 'mes'], name='receita_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['propriedade', 'ano'], name='receita_prop_ano_idx'),
        ),
        migrations.AddIndex(
            model_name='tokeninscricao',
            index=models.Index(fields=['data_criacao'], name='token_insc_data_criacao_idx'),
        ),
        migrations.AddIndex(
            model_name='tokeninscricao',
            index=models.Index(fields=['utilizado'], name='token_insc_utilizado_idx'),
        ),
        migrations.AddIndex(
            model_name='tokeninscricao',
            index=models.Index(fields=['usuario', 'utilizado'], name='token_insc_user_util_idx'),
        ),
        migrations.AddField(
            model_name='periodopersonalizado',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_personalizados', to='usuarios.lote', verbose_name='Lote'),
        ),
        migrations.AddIndex(
            model_name='periodopersonalizado',
            index=models.Index(fields=['lote', 'ano', 'mes'], name='periodo_pers_lote_ano_mes_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodopersonalizado',
            unique_together={('lote', 'mes', 'ano')},
        ),
    ]
